import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pathlib
from typing import Union

class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """
    
    def __init__(self, data_fname: Union[pathlib.Path, str]):
        if pathlib.Path(data_fname).is_file():
            self.data_fname=pathlib.Path(data_fname)
        else:
            raise ValueError

    def read_data(self):
        """
        Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        self.data_original=pd.read_json(self.data_fname)
        self.data=pd.read_json(self.data_fname)

    def show_age_distrib(self): #-> Tuple[np.ndarray, np.ndarray]
        """
        Calculates and plots the age distribution of the participants.
        Returns a tuple containing two numpy arrays:
        The first item being the number of people in a given bin.
        The second item being the bin edges.
        """
        hist=plt.hist(self.data["age"],bins=[0,10,20,30,40,50,60,70,80,90,100])
        plt.xlabel('Age')
        plt.ylabel('Number of participants')
        plt.show()
        return hist

    def remove_rows_without_mail(self): #-> pd.DataFrame
        """
        Checks self.data for rows with invalid emails, and removes them.
        Returns the corrected DataFrame, i.e. the same table but with
        the erroneous rows removed and the (ordinal) index after a reset.
        """
        self.data=self.data[self.data['email'].str.contains('@[a-zA-Z]+.c')]
        self.data.reset_index(drop=True, inplace=True)
        return self.data

    def fill_na_with_mean(self): #-> Union[pd.DataFrame, np.ndarray]
        """
        Finds, in the original DataFrame, the subjects that didn't answer
        all questions, and replaces that missing value with the mean of the
        other grades for that student. Returns the corrected DataFrame,
        as well as the row indices of the students that their new grades
        were generated.
        """
        row_NaN=np.array(self.data.index[self.data['q1'].isnull() | self.data['q2'].isnull()| self.data['q3'].isnull()| self.data['q4'].isnull()| self.data['q5'].isnull()])
        self.data=self.data.fillna(self.data.mean()['q1':'q5'])
        return [self.data, row_NaN]

    def correlate_gender_age(self): #-> pd.DataFrame
        """
        Looks for a correlation between the gender of the subject, their age
        and the score for all five questions.
        Returns a DataFrame with a MultiIndex containing the gender and whether
        the subject is above 40 years of age, and the average score in each of
        the five questions.
        """
        self.data_original['age over 40']=np.where(self.data_original['age']>40, 'True', 'False')
        self.data_original=self.data_original.set_index(['age', 'gender'], append=True)
        grouped=self.data_original.groupby(['gender','age over 40'])
        grouped_mean=grouped['q1','q2','q3','q4','q5'].mean()
        return grouped_mean



if __name__ == '__main__':
    data_fname="data.json"
    X=QuestionnaireAnalysis(data_fname)
    X.read_data()
    print(X.show_age_distrib())
    print(X.remove_rows_without_mail())
    print(X.fill_na_with_mean())
    print(X.correlate_gender_age())